[mcp_servers.one-mcp-common]
url = "http://127.0.0.1:3299/group/common/mcp?key=97dfc4de3db140c49ab7debee4b94703"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest", "--api-key", "ctx7sk-***"]

[mcp_servers.unityMCP]
command = "/Users/weekit/.local/bin/uvx"
args = ["--from", "mcpforunityserver==9.0.3", "mcp-for-unity", "--transport", "stdio"]
